export const questions = [
  {
    id: "foundations-model",
    category: "Foundations",
    prompt: "Which statements describe the GitHub Actions execution model?",
    options: ["Events can trigger workflows", "Jobs run on runners", "Steps can run commands or actions", "Every job shares one persistent filesystem", "Artifacts can carry files between jobs"],
    correct: [0, 1, 2, 4],
    explanation: "Events make workflows eligible, jobs execute on runners, steps run commands or actions, and artifacts carry files. Jobs should not assume a shared persistent filesystem.",
    source: { label: "Actions foundations — terminology", url: "curriculum/beginner/01-actions-foundations/README.md#foundations-and-terminology" },
  },
  {
    id: "foundations-events",
    category: "Foundations",
    prompt: "Which are valid ways to trigger a workflow?",
    options: ["A push to a selected branch", "A pull request activity type", "A manual workflow_dispatch run", "A scheduled cron event", "Only a local terminal command"],
    correct: [0, 1, 2, 3],
    explanation: "Push, pull request, manual dispatch, and schedule are workflow triggers. A local terminal command is not itself a GitHub Actions event.",
    source: { label: "Workflow syntax — on", url: "curriculum/beginner/02-workflow-syntax/README.md#on" },
  },
  {
    id: "foundations-runner",
    category: "Foundations",
    prompt: "Which runner guidelines are sound?",
    options: ["GitHub-hosted runners should be treated as fresh machines", "Jobs should explicitly check out and install what they need", "Self-hosted runners require stronger isolation", "A later job automatically sees the previous job's workspace", "Persistent self-hosted state can expand blast radius"],
    correct: [0, 1, 2, 4],
    explanation: "Hosted runners are disposable and jobs are isolated. Self-hosted runners persist and can reach more infrastructure, so their isolation and cleanup requirements are stronger.",
    source: { label: "Actions foundations — Runner", url: "curriculum/beginner/01-actions-foundations/README.md#runner" },
  },
  {
    id: "syntax-permissions",
    category: "Syntax & Expressions",
    prompt: "Which practices correctly reduce workflow permission risk?",
    options: ["Start with contents: read", "Elevate permissions only on the job that needs them", "Use id-token: write for OIDC token requests", "Grant contents: write to every test job", "Document why an elevated scope is needed"],
    correct: [0, 1, 2, 4],
    explanation: "Least privilege means a read-only baseline and narrow job-level elevation. OIDC needs id-token: write, while contents: write should not be granted to ordinary tests.",
    source: { label: "Workflow syntax — permissions", url: "curriculum/beginner/02-workflow-syntax/README.md#permissions" },
  },
  {
    id: "syntax-matrix",
    category: "Syntax & Expressions",
    prompt: "Which statements about a dynamic matrix are correct?",
    options: ["A consumer needs an explicit needs edge to read a producer job output", "fromJSON can convert a validated JSON output into matrix data", "max-parallel can bound simultaneous children", "User input should be allowed to select any runner label", "include and exclude adjust expanded combinations"],
    correct: [0, 1, 2, 4],
    explanation: "Job outputs require an explicit dependency, fromJSON creates the structured value, and matrix controls bound or adjust expansion. Untrusted input must not select arbitrary runners or unbounded axes.",
    source: { label: "Workflow syntax — Matrix strategies", url: "curriculum/beginner/02-workflow-syntax/README.md#matrix-strategies" },
  },
  {
    id: "syntax-injection",
    category: "Syntax & Expressions",
    prompt: "Which practices reduce shell-injection risk in workflows?",
    options: ["Pass event fields through environment variables", "Quote shell variable expansions", "Validate allowlisted values", "Interpolate arbitrary issue titles directly into run", "Prefer structured action inputs where possible"],
    correct: [0, 1, 2, 4],
    explanation: "Event fields are untrusted. Environment variables, quoting, validation, and structured inputs reduce shell interpretation risk; direct interpolation is dangerous.",
    source: { label: "Security — Template and shell injection", url: "curriculum/advanced/01-security-and-reliability/README.md#2-template-and-shell-injection" },
  },
  {
    id: "reuse-workflow",
    category: "Reuse & Scale",
    prompt: "What makes a reusable workflow interface maintainable?",
    options: ["Typed workflow_call inputs", "Explicitly declared secrets", "Documented outputs and permissions", "A large undocumented collection of implicit inputs", "Backwards-compatible changes"],
    correct: [0, 1, 2, 4],
    explanation: "Reusable workflows behave like APIs. Typed inputs, explicit secrets, documented outputs and permissions, and compatibility make callers predictable.",
    source: { label: "Scenario cookbook — Reusable organization workflow", url: "curriculum/intermediate/02-deployment-patterns/README.md#reusable-organization-workflow" },
  },
  {
    id: "reuse-cache-artifact",
    category: "Reuse & Scale",
    prompt: "Which statements distinguish caches from artifacts?",
    options: ["Caches speed up repeatable dependency downloads", "Artifacts preserve or pass job output", "Cache keys should include dependency identity", "Artifacts are a safe place for long-lived secrets", "Build outputs are usually better represented as artifacts"],
    correct: [0, 1, 2, 4],
    explanation: "Caches optimize repeatable inputs, while artifacts preserve outputs. Neither should contain secrets, and cache keys need dependency identity.",
    source: { label: "Workflow design — State and data movement", url: "curriculum/intermediate/01-workflow-design/README.md#state-and-data-movement" },
  },
  {
    id: "reuse-composite",
    category: "Reuse & Scale",
    prompt: "When is a reusable workflow a better fit than a composite action?",
    options: ["When packaging multiple jobs", "When the abstraction owns environments or matrices", "When callers need a typed secrets interface", "When packaging only a repeated step sequence", "When job-level permissions are part of the contract"],
    correct: [0, 1, 2, 4],
    explanation: "Reusable workflows package jobs and job-level orchestration. Composite actions package steps within the caller's job and are the simpler fit for step reuse.",
    source: { label: "Workflow design — Reuse boundaries", url: "curriculum/intermediate/01-workflow-design/README.md#reuse-boundaries-choose-the-smallest-honest-abstraction" },
  },
  {
    id: "design-selective-ci",
    category: "Workflow Design",
    prompt: "Which properties make an affected-service planner safe enough to skip work?",
    options: ["Propagate changes to transitive dependents", "Select all services for an unmapped code path", "Maintain labeled change cases and periodic full validation", "Treat documentation paths as affecting every service forever", "Record why each service was selected"],
    correct: [0, 1, 2, 4],
    explanation: "Safe selection follows dependencies, fails closed for unknown code, exposes reasons, and is continuously evaluated. Documentation can be explicitly classified without spending every service job.",
    source: { label: "Workflow design — Internal mechanics", url: "curriculum/intermediate/01-workflow-design/README.md#internal-mechanics-of-change-detection" },
  },
  {
    id: "design-cost-latency",
    category: "Workflow Design",
    prompt: "Which statements correctly compare workflow latency and runner consumption?",
    options: ["The critical path estimates idealized compute latency", "Parallel jobs still contribute to runner consumption", "max-parallel reduces the number of matrix jobs", "Queue and startup time add overhead beyond the DAG calculation", "Optimizing a non-critical job may save capacity without changing wall time"],
    correct: [0, 1, 3, 4],
    explanation: "Critical path and total work are different measures. max-parallel bounds simultaneous execution but does not remove jobs, while queueing and startup add observed latency.",
    source: { label: "Workflow design — Latency and capacity", url: "curriculum/intermediate/01-workflow-design/README.md#foundations-latency-capacity-and-selection-quality" },
  },
  {
    id: "design-required-gate",
    category: "Workflow Design",
    prompt: "How should a monorepo keep one trustworthy required check across dynamic fan-out?",
    options: ["Trigger a lightweight planner broadly", "Skip expensive jobs inside the graph", "Use a stable aggregate job that validates upstream conclusions", "Use always() and report success without inspecting needs", "Represent an empty plan explicitly"],
    correct: [0, 1, 2, 4],
    explanation: "The planner and aggregate check should exist for every relevant pull request. The gate must distinguish a deliberate empty plan from failed or unexpectedly skipped work.",
    source: { label: "Workflow design — Keep a required check present", url: "curriculum/intermediate/01-workflow-design/README.md#keep-a-required-check-present" },
  },
  {
    id: "deploy-artifact",
    category: "Deployment",
    prompt: "What does build-once, promote-many-times mean?",
    options: ["Build one immutable artifact", "Test or scan that artifact", "Deploy the same artifact to staging and production", "Rebuild independently during production deployment", "Keep the artifact tied to a commit or checksum"],
    correct: [0, 1, 2, 4],
    explanation: "Build once, verify, and promote the same immutable output. Rebuilding at deploy time can produce a different, untested input.",
    source: { label: "Deployment patterns — Build once", url: "curriculum/intermediate/02-deployment-patterns/README.md#build-once-promote-many-times" },
  },
  {
    id: "deploy-environment",
    category: "Deployment",
    prompt: "Which controls make an uncertain or unhealthy production deployment recoverable?",
    options: ["A stable idempotency key bound to the digest", "Authoritative state reconciliation before retry", "Compare-and-swap rollback", "Turning the workflow green after rollback", "A concurrency policy shared by every mutating workflow"],
    correct: [0, 1, 2, 4],
    explanation: "Deployment safety requires deduplication, reconciliation, serialization, and rollback that cannot overwrite a newer state. A successful rollback mitigates impact but should not hide the failed release.",
    source: { label: "Deployment patterns — Idempotency and uncertain writes", url: "curriculum/intermediate/02-deployment-patterns/README.md#idempotency-and-uncertain-writes" },
  },
  {
    id: "deploy-oidc",
    category: "Deployment",
    prompt: "Which statements about OIDC cloud deployment are correct?",
    options: ["The job needs id-token: write", "Cloud trust should restrict repository and branch/environment claims", "OIDC can avoid long-lived cloud keys", "The workflow should print the identity token for debugging", "The permission can be limited to the deploy job"],
    correct: [0, 1, 2, 4],
    explanation: "OIDC uses a short-lived token, requires id-token: write, and should be constrained by cloud trust conditions. Tokens must never be printed.",
    source: { label: "Deployment patterns — Cloud deployment with OIDC", url: "curriculum/intermediate/02-deployment-patterns/README.md#cloud-deployment-with-oidc" },
  },
  {
    id: "security-forks",
    category: "Security & Reliability",
    prompt: "Which statements correctly close a pwn-request attack path?",
    options: ["Use read-only pull_request validation for fork code", "Keep privileged metadata handling separate from fork execution", "Treat workflow_run artifacts from forks as untrusted data", "Rely on checkout v7 while deliberately executing the fork with write authority", "Restrict the event centrally when pull_request_target is unnecessary"],
    correct: [0, 1, 2, 4],
    explanation: "The architecture must separate untrusted code from authority. Checkout protections are defense in depth and do not make privileged fork execution safe.",
    source: { label: "Security — Workflow identity and source selection", url: "curriculum/advanced/01-security-and-reliability/README.md#workflow-identity-and-source-selection" },
  },
  {
    id: "security-pinning",
    category: "Security & Reliability",
    prompt: "Which statements correctly describe action dependency assurance?",
    options: ["A reviewed full SHA prevents the selected ref from moving", "A version comment helps reviewers and dependency automation", "The action's source, transitive code, permissions, and egress still require review", "A full SHA proves the action is vulnerability-free", "Privileged jobs should minimize third-party executable code"],
    correct: [0, 1, 2, 4],
    explanation: "SHA pinning provides immutable selection, not complete trust. Review the code and release process, bound authority and network access, and keep privileged dependency sets small.",
    source: { label: "Security — Action dependency compromise", url: "curriculum/advanced/01-security-and-reliability/README.md#3-action-and-reusable-workflow-dependency-compromise" },
  },
  {
    id: "security-reliability",
    category: "Security & Reliability",
    prompt: "What makes a multi-job security gate fail closed without blocking valid non-PR runs?",
    options: ["A stable aggregate job that inspects every applicable upstream result", "An explicit acceptable skipped state for event-specific jobs", "Negative authorization tests for unsafe requests", "continue-on-error on every scanner", "Timeouts and bounded, reconciled retries for side effects"],
    correct: [0, 1, 2, 4],
    explanation: "The aggregate gate must distinguish intentional skips from failures, enforce negative cases, and bound unreliable work. Making scanners advisory through continue-on-error defeats the gate.",
    source: { label: "Security — Reliability controls", url: "curriculum/advanced/01-security-and-reliability/README.md#reliability-controls-are-security-controls" },
  },
  {
    id: "operations-debug",
    category: "Operations",
    prompt: "Which evidence belongs at the start of a workflow failure investigation?",
    options: ["Run ID and run attempt", "Source SHA and workflow revision", "The first job or step that diverged", "Only the last red step in the cascade", "Runner and dependency identities"],
    correct: [0, 1, 2, 4],
    explanation: "Identity and the first divergent node distinguish the cause from downstream symptoms. A rerun attempt, source, workflow definition, runner, and dependencies can all change the interpretation.",
    source: { label: "Debugging and operations — systematic investigation", url: "curriculum/advanced/02-debugging-and-operations/README.md#a-systematic-investigation-method" },
  },
  {
    id: "operations-schedule",
    category: "Operations",
    prompt: "Which statements make a scheduled-workflow SLO meaningful?",
    options: ["Count expected schedule slots, including slots with no run", "Separate schedule delivery from execution success", "Document timezone and avoid known high-load boundaries", "Calculate delivery using only runs that already exist", "Use an idempotent externally dispatched path when timing guarantees are required"],
    correct: [0, 1, 2, 4],
    explanation: "GitHub schedules can be delayed or dropped, so expected slots must be modeled independently. Delivery and execution success answer different questions; stronger timing guarantees need an external scheduler and idempotent dispatch.",
    source: { label: "Debugging and operations — schedule delivery", url: "curriculum/advanced/02-debugging-and-operations/README.md#schedule-delivery" },
  },
  {
    id: "operations-observe",
    category: "Operations",
    prompt: "Which practices preserve useful operational evidence without creating a new security problem?",
    options: ["Name artifacts with run ID and attempt", "Retain structured reports with source and expiry metadata", "Use filter=all when retrieving jobs across attempts", "Dump complete contexts and environments into logs", "Record metrics populations and raw calculation inputs"],
    correct: [0, 1, 2, 4],
    explanation: "Attempt-aware artifacts, structured provenance, complete attempt retrieval, and reproducible metric inputs support investigation. Complete context or environment dumps can expose sensitive data.",
    source: { label: "Debugging and operations — instrumentation mechanics", url: "curriculum/advanced/02-debugging-and-operations/README.md#instrumentation-mechanics" },
  },
];
