export const questions = [
  {
    id: "foundations-model",
    category: "Foundations",
    prompt: "Which statements describe the GitHub Actions execution model?",
    options: ["Events can trigger workflows", "Jobs run on runners", "Steps can run commands or actions", "Every job shares one persistent filesystem", "Artifacts can carry files between jobs"],
    correct: [0, 1, 2, 4],
    explanation: "Events make workflows eligible, jobs execute on runners, steps run commands or actions, and artifacts carry files. Jobs should not assume a shared persistent filesystem.",
    source: { label: "Actions foundations — terminology", url: "curriculum/beginner/01-actions-foundations/README.md#foundations-and-terminology" },
  },
  {
    id: "foundations-events",
    category: "Foundations",
    prompt: "Which are valid ways to trigger a workflow?",
    options: ["A push to a selected branch", "A pull request activity type", "A manual workflow_dispatch run", "A scheduled cron event", "Only a local terminal command"],
    correct: [0, 1, 2, 3],
    explanation: "Push, pull request, manual dispatch, and schedule are workflow triggers. A local terminal command is not itself a GitHub Actions event.",
    source: { label: "Workflow syntax — on", url: "curriculum/beginner/02-workflow-syntax/README.md#on" },
  },
  {
    id: "foundations-runner",
    category: "Foundations",
    prompt: "Which runner guidelines are sound?",
    options: ["GitHub-hosted runners should be treated as fresh machines", "Jobs should explicitly check out and install what they need", "Self-hosted runners require stronger isolation", "A later job automatically sees the previous job's workspace", "Persistent self-hosted state can expand blast radius"],
    correct: [0, 1, 2, 4],
    explanation: "Hosted runners are disposable and jobs are isolated. Self-hosted runners persist and can reach more infrastructure, so their isolation and cleanup requirements are stronger.",
    source: { label: "Actions foundations — Runner", url: "curriculum/beginner/01-actions-foundations/README.md#runner" },
  },
  {
    id: "syntax-permissions",
    category: "Syntax & Expressions",
    prompt: "Which practices correctly reduce workflow permission risk?",
    options: ["Start with contents: read", "Elevate permissions only on the job that needs them", "Use id-token: write for OIDC token requests", "Grant contents: write to every test job", "Document why an elevated scope is needed"],
    correct: [0, 1, 2, 4],
    explanation: "Least privilege means a read-only baseline and narrow job-level elevation. OIDC needs id-token: write, while contents: write should not be granted to ordinary tests.",
    source: { label: "Workflow syntax — permissions", url: "curriculum/beginner/02-workflow-syntax/README.md#permissions" },
  },
  {
    id: "syntax-matrix",
    category: "Syntax & Expressions",
    prompt: "Which statements about a dynamic matrix are correct?",
    options: ["A consumer needs an explicit needs edge to read a producer job output", "fromJSON can convert a validated JSON output into matrix data", "max-parallel can bound simultaneous children", "User input should be allowed to select any runner label", "include and exclude adjust expanded combinations"],
    correct: [0, 1, 2, 4],
    explanation: "Job outputs require an explicit dependency, fromJSON creates the structured value, and matrix controls bound or adjust expansion. Untrusted input must not select arbitrary runners or unbounded axes.",
    source: { label: "Workflow syntax — Matrix strategies", url: "curriculum/beginner/02-workflow-syntax/README.md#matrix-strategies" },
  },
  {
    id: "syntax-injection",
    category: "Syntax & Expressions",
    prompt: "Which practices reduce shell-injection risk in workflows?",
    options: ["Pass event fields through environment variables", "Quote shell variable expansions", "Validate allowlisted values", "Interpolate arbitrary issue titles directly into run", "Prefer structured action inputs where possible"],
    correct: [0, 1, 2, 4],
    explanation: "Event fields are untrusted. Environment variables, quoting, validation, and structured inputs reduce shell interpretation risk; direct interpolation is dangerous.",
    source: { label: "Security — Shell injection", url: "curriculum/advanced/01-security-and-reliability/README.md#shell-injection" },
  },
  {
    id: "reuse-workflow",
    category: "Reuse & Scale",
    prompt: "What makes a reusable workflow interface maintainable?",
    options: ["Typed workflow_call inputs", "Explicitly declared secrets", "Documented outputs and permissions", "A large undocumented collection of implicit inputs", "Backwards-compatible changes"],
    correct: [0, 1, 2, 4],
    explanation: "Reusable workflows behave like APIs. Typed inputs, explicit secrets, documented outputs and permissions, and compatibility make callers predictable.",
    source: { label: "Scenario cookbook — Reusable organization workflow", url: "curriculum/intermediate/02-deployment-patterns/README.md#reusable-organization-workflow" },
  },
  {
    id: "reuse-cache-artifact",
    category: "Reuse & Scale",
    prompt: "Which statements distinguish caches from artifacts?",
    options: ["Caches speed up repeatable dependency downloads", "Artifacts preserve or pass job output", "Cache keys should include dependency identity", "Artifacts are a safe place for long-lived secrets", "Build outputs are usually better represented as artifacts"],
    correct: [0, 1, 2, 4],
    explanation: "Caches optimize repeatable inputs, while artifacts preserve outputs. Neither should contain secrets, and cache keys need dependency identity.",
    source: { label: "Core concepts — Caches versus artifacts", url: "curriculum/intermediate/01-workflow-design/README.md#caches-versus-artifacts" },
  },
  {
    id: "reuse-composite",
    category: "Reuse & Scale",
    prompt: "When is a reusable workflow a better fit than a composite action?",
    options: ["When packaging multiple jobs", "When the abstraction owns environments or matrices", "When callers need a typed secrets interface", "When packaging only a repeated step sequence", "When job-level permissions are part of the contract"],
    correct: [0, 1, 2, 4],
    explanation: "Reusable workflows package jobs and job-level orchestration. Composite actions package steps within the caller's job and are the simpler fit for step reuse.",
    source: { label: "Core concepts — Reusable workflows versus composite actions", url: "curriculum/intermediate/01-workflow-design/README.md#reusable-workflows-versus-composite-actions" },
  },
  {
    id: "deploy-artifact",
    category: "Deployment",
    prompt: "What does build-once, promote-many-times mean?",
    options: ["Build one immutable artifact", "Test or scan that artifact", "Deploy the same artifact to staging and production", "Rebuild independently during production deployment", "Keep the artifact tied to a commit or checksum"],
    correct: [0, 1, 2, 4],
    explanation: "Build once, verify, and promote the same immutable output. Rebuilding at deploy time can produce a different, untested input.",
    source: { label: "Core concepts — Build once", url: "curriculum/intermediate/01-workflow-design/README.md#build-once-promote-the-same-artifact" },
  },
  {
    id: "deploy-environment",
    category: "Deployment",
    prompt: "Which controls belong on a production deployment?",
    options: ["A protected GitHub environment", "Required reviewers or branch restrictions", "A concurrency group for the production resource", "Production credentials in every pull-request job", "A clear rollback or cancellation policy"],
    correct: [0, 1, 2, 4],
    explanation: "Environments, review rules, concurrency, and rollback policy protect production. Pull-request test jobs should not receive production credentials.",
    source: { label: "Security — Environments", url: "curriculum/advanced/01-security-and-reliability/README.md#environments" },
  },
  {
    id: "deploy-oidc",
    category: "Deployment",
    prompt: "Which statements about OIDC cloud deployment are correct?",
    options: ["The job needs id-token: write", "Cloud trust should restrict repository and branch/environment claims", "OIDC can avoid long-lived cloud keys", "The workflow should print the identity token for debugging", "The permission can be limited to the deploy job"],
    correct: [0, 1, 2, 4],
    explanation: "OIDC uses a short-lived token, requires id-token: write, and should be constrained by cloud trust conditions. Tokens must never be printed.",
    source: { label: "Scenario cookbook — Cloud deployment with OIDC", url: "curriculum/intermediate/02-deployment-patterns/README.md#cloud-deployment-with-oidc" },
  },
  {
    id: "security-forks",
    category: "Security & Reliability",
    prompt: "Which statements about fork pull requests are correct?",
    options: ["Fork code can change tests and dependency hooks", "pull_request jobs should avoid secrets", "pull_request_target can have base-repo privileges", "It is safe to execute fork code in a privileged pull_request_target job", "The trust boundary should be documented"],
    correct: [0, 1, 2, 4],
    explanation: "Fork code is untrusted. pull_request is safer for validation; pull_request_target has base-repository context and must never blindly execute fork code.",
    source: { label: "Security — Untrusted pull requests", url: "curriculum/advanced/01-security-and-reliability/README.md#untrusted-pull-requests" },
  },
  {
    id: "security-pinning",
    category: "Security & Reliability",
    prompt: "Which actions-security practices are recommended?",
    options: ["Pin third-party actions to reviewed full SHAs", "Keep a human-readable version comment", "Review action updates deliberately", "Assume a mutable major tag cannot change", "Use least-privilege permissions"],
    correct: [0, 1, 2, 4],
    explanation: "Full SHA pinning reduces mutable-tag drift, while comments and deliberate updates preserve maintainability. Least privilege limits impact if something fails.",
    source: { label: "Security — Pin actions", url: "curriculum/advanced/01-security-and-reliability/README.md#pin-actions" },
  },
  {
    id: "security-reliability",
    category: "Security & Reliability",
    prompt: "Which controls make workflow side effects safer to retry?",
    options: ["Timeouts", "Concurrency groups", "Idempotency keys or state checks", "Blindly retrying a release after a timeout", "External verification and reconciliation"],
    correct: [0, 1, 2, 4],
    explanation: "Timeouts, serialized runs, idempotency, verification, and reconciliation bound and recover side effects. Blind retries can duplicate an uncertain write.",
    source: { label: "Security — Reliability controls", url: "curriculum/advanced/01-security-and-reliability/README.md#reliability-controls" },
  },
  {
    id: "operations-debug",
    category: "Operations",
    prompt: "What should you check first when a workflow fails?",
    options: ["The first failed step", "Event, branch, commit, actor, and workflow revision", "Permissions and environment approvals", "Only the final summary line", "Runner OS, tool versions, and working directory"],
    correct: [0, 1, 2, 4],
    explanation: "The first failure and run metadata establish the cause. Permissions, approvals, runner, versions, and directory often explain CI-only failures.",
    source: { label: "Debugging — Read a failed run systematically", url: "curriculum/advanced/02-debugging-and-operations/README.md#read-a-failed-run-systematically" },
  },
  {
    id: "operations-schedule",
    category: "Operations",
    prompt: "Which practices improve scheduled maintenance workflows?",
    options: ["Use UTC and document the schedule", "Make the operation idempotent", "Use a low-privilege token", "Assume scheduled runs can never be delayed", "Notify or create an issue on failure"],
    correct: [0, 1, 2, 4],
    explanation: "Schedules can be delayed or duplicated. UTC documentation, idempotency, least privilege, and failure notification make maintenance operable.",
    source: { label: "Scenario cookbook — Scheduled maintenance", url: "curriculum/intermediate/02-deployment-patterns/README.md#scheduled-maintenance" },
  },
  {
    id: "operations-observe",
    category: "Operations",
    prompt: "Which metadata is useful for investigating an important workflow?",
    options: ["Commit and workflow/action versions", "Artifact names and checksums", "Actor, event, environment, and deployment ID", "Secret values and full environment dumps", "Duration and failure category"],
    correct: [0, 1, 2, 4],
    explanation: "Versions, provenance, actors, environments, IDs, duration, and failure categories support investigation. Secret values must not be logged.",
    source: { label: "Debugging — Observability", url: "curriculum/advanced/02-debugging-and-operations/README.md#observability" },
  },
];
